# Info about Inertia's version

# Major
if(NOT DEFINED INERTIA_VERSION_MAJOR)
    set(INERTIA_VERSION_MAJOR 0)
endif()

# Minor
if(NOT DEFINED INERTIA_VERSION_MINOR)
    set(INERTIA_VERSION_MINOR 0)
endif()

# Patch
if(NOT DEFINED INERTIA_VERSION_PATCH)
    set(INERTIA_VERSION_PATCH 1)
endif()